<?php

class FFLTableSeeder extends Seeder
{

	public function run()
	{
		DB::table('ffls')->delete();
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '02','lic_xprdte' => '6D','lic_segn' => '01790','license_name' => 'HY & MIKES OF OGDEN INC','business_name' => 'HY & MIKES LAYTON','premise_street' => '689 N MAIN','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => '689 N MAIN','mail_city' => 'LAYTON','mail_state' => 'UT','mail_zip_code' => '84041','phone' => '8015441055','user_id' => '8'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '06','lic_xprdte' => '7A','lic_segn' => '01506','license_name' => 'SETPOINT AMMO','business_name' => 'NULL','premise_street' => '196 SUGAR ST # 1','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => '196 SUGAR ST # 1','mail_city' => 'LAYTON','mail_state' => 'UT','mail_zip_code' => '84041','phone' => '8553082666'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '01','lic_xprdte' => '6G','lic_segn' => '02159','license_name' => 'LONG SHOT CONSULTING LLC','business_name' => 'NULL','premise_street' => '231 N 3425 W','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => '231 N 3425 W','mail_city' => 'LAYTON','mail_state' => 'UT','mail_zip_code' => '84041','phone' => '8016457000'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '07','lic_xprdte' => '5G','lic_segn' => '01869','license_name' => 'RED DOT FIREARMS LLC','business_name' => 'RED DOT FIREARMS','premise_street' => '990 W HILL FIELD RD','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => '990 W HILL FIELD RD','mail_city' => 'LAYTON','mail_state' => 'UT','mail_zip_code' => '84041','phone' => '8019234199'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '01','lic_xprdte' => '7J','lic_segn' => '01708','license_name' => 'DICK\'S SPORTING GOODS, INC.','business_name' => 'DICK\'S SPORTING GOODS, INC.','premise_street' => '1201 N HILL FIELD ROAD #1024','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => '345 COURT ST','mail_city' => 'CORAOPOLIS','mail_state' => 'PA','mail_zip_code' => '15108','phone' => '8014446656'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '06','lic_xprdte' => '7F','lic_segn' => '02494','license_name' => 'NEXUS AMMO LLC','business_name' => 'NULL','premise_street' => '196 N SUAGR ST #1','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => '23606 N 19TH AVE STE 10','mail_city' => 'PHOENIX','mail_state' => 'AZ','mail_zip_code' => '85085','phone' => '6237801050'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '01','lic_xprdte' => '6J','lic_segn' => '34969','license_name' => 'BIG 5 CORP','business_name' => 'BIG 5 SPORTING GOODS #231','premise_street' => '1130 N MAIN ST','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => 'PO BOX 92088','mail_city' => 'LOS ANGELES','mail_state' => 'CA','mail_zip_code' => '90009','phone' => '3105360611'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '01','lic_xprdte' => '5J','lic_segn' => '84252','license_name' => 'ALMAGUER, EDWARD LEE','business_name' => 'E & L PERSONALS','premise_street' => '267 FRANCIS AVE','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => '267 FRANCIS AVE','mail_city' => 'LAYTON','mail_state' => 'UT','mail_zip_code' => '84041','phone' => '8015444836'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '06','lic_xprdte' => '5C','lic_segn' => '35055','license_name' => 'CHOKE AMMUNITION LLC','business_name' => 'NULL','premise_street' => '105 WHITE SIDES ST','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => 'PO BOX 241','mail_city' => 'LAYTON','mail_state' => 'UT','mail_zip_code' => '84041','phone' => '8014970817'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '01','lic_xprdte' => '5D','lic_segn' => '01146','license_name' => 'PROFESSIONAL FIREARMS INSTRUCTION LLC','business_name' => 'FIREARMSPRO','premise_street' => '1596 N HILLFIELD RD STE G','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => '1596 N HILLFIELD RD STE G','mail_city' => 'LAYTON','mail_state' => 'UT','mail_zip_code' => '84041','phone' => '8014160606'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '01','lic_xprdte' => '7E','lic_segn' => '06912','license_name' => 'EVANS, ROBERT J','business_name' => 'BOBS CUSTOM GUNS','premise_street' => '2369 N FORT LN','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => '2369 N FORT LN','mail_city' => 'LAYTON','mail_state' => 'UT','mail_zip_code' => '84041','phone' => '8017763941'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '07','lic_xprdte' => '7G','lic_segn' => '35016','license_name' => 'HANSEN, B SHAWN','business_name' => 'THE FIRING LINE','premise_street' => '1091 W 2200 N','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => '1091 W 2200 N','mail_city' => 'LAYTON','mail_state' => 'UT','mail_zip_code' => '84041','phone' => '8018259235'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '011','lic_type' => '01','lic_xprdte' => '7G','lic_segn' => '01605','license_name' => 'C A L STORES COMPANIES INCORPORATED','business_name' => 'C A L RANCH STORES','premise_street' => '88 SOUTH FAIRFIELD ROAD','premise_city' => 'LAYTON','premise_state' => 'UT','premise_zip_code' => '84041','mail_street' => 'P O BOX 1866 665 E ANDERSON ST','mail_city' => 'IDAHO FALLS','mail_state' => 'ID','mail_zip_code' => '83403','phone' => '8015432044'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '07','lic_xprdte' => '6H','lic_segn' => '02187','license_name' => 'MOXO LLC','business_name' => 'MOXO','premise_street' => '1077 W 500 NORTH','premise_city' => 'LINDON','premise_state' => 'UT','premise_zip_code' => '84042','mail_street' => '881 W STATE RD STE 104-512','mail_city' => 'PLEASANT GROVE','mail_state' => 'UT','mail_zip_code' => '84062','phone' => '8018503705'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '01','lic_xprdte' => '5E','lic_segn' => '01829','license_name' => 'REHKOP, BURTON D','business_name' => 'REHKOP ENTERPRISES','premise_street' => '261 QUEENSLAND COURT','premise_city' => 'LINDON','premise_state' => 'UT','premise_zip_code' => '84042','mail_street' => '261 QUEENSLAND COURT','mail_city' => 'LINDON','mail_state' => 'UT','mail_zip_code' => '84042','phone' => '8016028226'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '02','lic_xprdte' => '5G','lic_segn' => '01877','license_name' => 'PAWN SOLUTIONS','business_name' => 'XTREME PAWN','premise_street' => '720 N STATE ST','premise_city' => 'LINDON','premise_state' => 'UT','premise_zip_code' => '84042','mail_street' => '720 N STATE ST','mail_city' => 'LINDON','mail_state' => 'UT','mail_zip_code' => '84042','phone' => '8017968612'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '01','lic_xprdte' => '7E','lic_segn' => '34780','license_name' => 'STANWORTH, REX D','business_name' => 'STANWORTH GUN SHOP','premise_street' => '391 W 250S','premise_city' => 'LINDON','premise_state' => 'UT','premise_zip_code' => '84042','mail_street' => '391 W 250 SOUTH','mail_city' => 'LINDON','mail_state' => 'UT','mail_zip_code' => '84042','phone' => '8014267856'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '07','lic_xprdte' => '5F','lic_segn' => '00020','license_name' => 'TRIOX TECHNOLOGIES INC','business_name' => 'NULL','premise_street' => '555 SOUTH GENEVA RD','premise_city' => 'LINDON','premise_state' => 'UT','premise_zip_code' => '84042','mail_street' => 'PO BOX 370','mail_city' => 'PLEASANT GROVE','mail_state' => 'UT','mail_zip_code' => '84062','phone' => '8014005526'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '07','lic_xprdte' => '8B','lic_segn' => '02726','license_name' => 'SPECTRE, LLC','business_name' => 'TIMP TACTICAL','premise_street' => '555 SOUTH GENEVA RD','premise_city' => 'LINDON','premise_state' => 'UT','premise_zip_code' => '84042','mail_street' => 'P O BOX 370','mail_city' => 'PLEASANT GROVE','mail_state' => 'UT','mail_zip_code' => '84062','phone' => '8014005561'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '07','lic_xprdte' => '7E','lic_segn' => '02461','license_name' => 'SRCONLIN LLP','business_name' => 'CONLIN ARMS','premise_street' => '5165 N EAGLES VIEW DR','premise_city' => 'LEHI','premise_state' => 'UT','premise_zip_code' => '84043','mail_street' => '5165 N EAGLES VIEW DR','mail_city' => 'LEHI','mail_state' => 'UT','mail_zip_code' => '84043','phone' => '8015180247'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '07','lic_xprdte' => '6L','lic_segn' => '02284','license_name' => 'MORRILL, MARTY AARON','business_name' => 'NEANDERTHAL ARMORY','premise_street' => '170 WEST STATE STREET','premise_city' => 'LEHI','premise_state' => 'UT','premise_zip_code' => '84043','mail_street' => '170 WEST STATE STREET','mail_city' => 'LEHI','mail_state' => 'UT','mail_zip_code' => '84043','phone' => '8014274475'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '01','lic_xprdte' => '5D','lic_segn' => '00804','license_name' => 'GALBREATH, WILLIAM ROBERT','business_name' => 'R A E S II','premise_street' => '2852 W WILLOW PATCH RD','premise_city' => 'LEHI','premise_state' => 'UT','premise_zip_code' => '84043','mail_street' => 'PO BOX 826','mail_city' => 'LEHI','mail_state' => 'UT','mail_zip_code' => '84043','phone' => '8013692209'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '08','lic_xprdte' => '5L','lic_segn' => '00460','license_name' => 'CONDE, STEPHEN D','business_name' => 'S D CONDE','premise_street' => '801 SOUTH 2475 WEST','premise_city' => 'LEHI','premise_state' => 'UT','premise_zip_code' => '84043','mail_street' => '801 SOUTH 2475 WEST','mail_city' => 'LEHI','mail_state' => 'UT','mail_zip_code' => '84043','phone' => '8019016944'));
		FFL::create(array('lic_regn' => '9','lic_dist' => '87','lic_cnty' => '049','lic_type' => '01','lic_xprdte' => '6L','lic_segn' => '02311','license_name' => 'GUN SMARTS LLC','business_name' => 'GUN SMARTS','premise_street' => '455 W 2925 N','premise_city' => 'LEHI','premise_state' => 'UT','premise_zip_code' => '84043','mail_street' => '455 W 2925 N','mail_city' => 'LEHI','mail_state' => 'UT','mail_zip_code' => '84043','phone' => '8015977892'));
	}

}